### ISSUE TITLE
Font value calculation

### ISSUE THREAD

**Issue by jadnco** [jadnco/jadnco.github.io#2]
Something weird is going on after updating `gulp-sass`.

This `font` function defined:

``` scss
$font-family: Inconsolata, monospace;

@function font($fs, $family: $font-family) {
  @return #{map-get($font-size, $fs) + ' ' + $family};
}
```

The `font-size` map defined:

``` scss
$font-size: (
  default: 16px/1.35
)
```

In the stylesheet I have this:

``` scss
body {
  font: font(default);
}
```

And I would expect to get this:

``` scss
body {
  font: 16px/1.35 Inconsolata, monospace;
}
```

But am getting this:

``` scss
body {
  font: 11.851px Inconsolata, monospace;
}
```

Division is happening between the font-size and the line-height values, which should not be happening.
